const productTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  UPDATE_PRODUCT_START: "UPDATE_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  SET_PRODUCT: "SET_PRODUCT",

  ADD_NEW_CATEGORY_START: "ADD_NEW_CATEGORY_START",
  UPDATE_CATEGORY_START: "UPDATE_CATEGORY_START",
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  SET_CATEGORIES: "SET_CATEGORIES",
  DELETE_CATEGORY_START: "DELETE_CATEGORY_START",
  FETCH_CATEGORY_START: "FETCH_CATEGORY_START",
  SET_CATEGORY: "SET_CATEGORY",
};

export default productTypes;
