const userTypes = {
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_USER_START: "SIGN_OUT_USER_START",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  RECOVER_PASSWORD_START: "RECOVER_PASSWORD_START",
  RECOVER_PASSWORD_SUCCESS: "RECOVER_PASSWORD_SUCCESS",
  USER_ERROR: "USER_ERROR",
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  IS_LOADING: "IS_LOADING",
};

export default userTypes;
